In [1]:
# importações bibliotecas

# pip install -q numpy==2.3.2

import numpy as np
import math
import time

In [2]:
# Criando uma lista(vetor) com numpy de 10 milhões de itens

import numpy
import math
import time

precos_np = np.random.rand(10_000_000)
type(precos_np)

numpy.ndarray

In [5]:
precos_np

array([0.50445673, 0.94996241, 0.89961819, ..., 0.9263436 , 0.96771972,
       0.19396487])

In [4]:
# Cria uma lista (estrutura de dados em Padrão Python puro)

precos_list = list(precos_np)
type(precos_list)


list

In [6]:
t0 = time.time()
desc = precos_np * 0.9
final = desc + 5
raiz = np.sqrt(precos_np)
print("Numpy:", time.time() - t0, "segundos")

Numpy: 0.08912158012390137 segundos


In [9]:
# Mesma operação com Python puro

t0 = time.time()
desc = [p * 0.9 for p in precos_list]
final = [p + 5 for p in desc]
raiz = [ math.sqrt(p) for p in precos_list]
print(f"Python puro: {time.time() - t0} segundos ")

Python puro: 4.127810001373291 segundos 


In [10]:
vetor = np.array([17, 21, 100, 34])
print("\nVetor (Array 1D):\n")
print(vetor)


Vetor (Array 1D):

[ 17  21 100  34]


In [11]:
# verificando atributos

print("Formato (shape) do vetor:", vetor.shape)
print("Número de dimensões (ndim) do vetor:", vetor.ndim)
print("Número total de dimensões (size) do vetor:", vetor.size)

Formato (shape) do vetor: (4,)
Número de dimensões (ndim) do vetor: 1
Número total de dimensões (size) do vetor: 4


In [12]:
# Criando um array de 2 dimensões (matriz) a partir de uma lista de listas

matriz = np.array([[1,2,3],[4,5,6]])
print("\nMatriz (Array 2D): \n")
print(matriz)


Matriz (Array 2D): 

[[1 2 3]
 [4 5 6]]


In [13]:
# verificando atributos

print("Formato (shape) do vetor:", matriz.shape) # linhas e colunas
print("Número de dimensões (ndim) do vetor:", matriz.ndim)
print("Número total de dimensões (size) do vetor:", matriz.size)

Formato (shape) do vetor: (2, 3)
Número de dimensões (ndim) do vetor: 2
Número total de dimensões (size) do vetor: 6


In [ ]:
# Criando um array 3D usando np.arange()

arr = np.arange(24).reshape(4,3,2)
print("\nArray (Array 3D): \n")
print(arr)

In [15]:
# verificando atributos

print("Formato (shape) do vetor:", arr.shape)
print("Número de dimensões (ndim) do vetor:", arr.ndim)
print("Número total de dimensões (size) do vetor:", arr.size)

Formato (shape) do vetor: (4, 3, 2)
Número de dimensões (ndim) do vetor: 3
Número total de dimensões (size) do vetor: 24


In [18]:
# NumPy infere o tipo de dado automaticamente

arr_inteiros = np.array([1,2,3])
print(f"Tipo de dado (int): {arr_inteiros.dtype}")

Tipo de dado (int): int64


In [17]:
# NumPy infere o tipo de dado automaticamente

arr_float = np.array([1.0,2.0,3.0])
print(f"Tipo de dado (float): {arr_float.dtype}")

Tipo de dado (int): float64


In [19]:
# Mas podemos especificar o tipo de dado durante a criação

arr_float = np.array([1,2,3], dtype=np.float64)
print(f"Tipo de dado (float64): {arr_float.dtype}")
print(f"Array float: {arr_float}")

Tipo de dado (float64): float64
Array float: [1. 2. 3.]


In [20]:
# conversão para int64

arr_int = arr_float.astype(np.int64)
print(f"Tipo convertido: {arr_int.dtype}")
print(f"Array convertido: {arr_int}")

Tipo convertido: int64
Array convertido: [1 2 3]


In [21]:
# Vamos criar uma matriz 4x4 com números de 0 a 15

dados = np.arange(16).reshape(4,4)
print("\nMatriz Original: \n")
print(dados)



Matriz Original: 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [22]:
# Acessando um elemento especifico: linha 1, coluna 2(lembre-se que a indexação em Python começa em 0)
print("\nMatriz Original: \n")
print(dados)
elemento = dados[1,2]
print(f"\nElemento na posição [1,2]: {elemento}")


Matriz Original: 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Elemento na posição [1,2]: 6
